services:
  edgedb:
    image: edgedb/edgedb:latest
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_USER: edgedb
      EDGEDB_SERVER_PASSWORD: edgedb
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"

